project:
  type: website
  output-dir: docs
  resources: 
    - "*.xlsx"
    - "*.csv"
    - "*.ipynb"
    
website:
  title: "Balázs Kocsis Blog"
  favicon: icon.png
  search: 
    location: navbar
    type: overlay
  bread-crumbs: true 
  twitter-card: true
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: book-shelf.qmd
        text: Book Shelf
      - icon: rss
        text: RSS
        href: index.xml
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/kocsisbalazs/kocsisbalazs.github.io
          - text: Report a Bug
            href: https://github.com/kocsisbalazs/kocsisbalazs.github.io/issues
  page-footer:
    center: "© 2024 Balázs Kocsis. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."

format:
  html:
    theme: default
    css: styles.css

editor: visual